version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "build:"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "monthly"
        time: "09:00"
        timezone: "Europe/Oslo"
    commit-message:
      prefix: "ci:"
    groups:
      all:
        patterns:
          - "*"