name: Build and deploy container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://discordbotspricecheck.azurecr.io/
        username: ${{ secrets.AZR_USERNAME }}
        password: ${{ secrets.AZR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: discordbotspricecheck.azurecr.io/${{ secrets.AZR_USERNAME }}/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      CRYPTO: 'ETH'
      CRYPTOGECKO: 'ethereum'


    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'notfier-nok'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_810c5c2acf94469299a5426ebef7c892 }}
        images: 'discordbotspricecheck.azurecr.io/${{ secrets.AZR_USERNAME }}/latest:${{ github.sha }}'